setup.py

Solves issue #16. I added the script to the repo but not to the setup scripts.

add merge_stars to setup

---

README.md

Solves issue #10.
Citation still needs to be added (added issue #18 for that).

added install instructions to README

---

README.md

Added citation details

---

src/pytom_tm/extract.py

Draft PR for making the starfiles more descriptive. Closes #37 and closes #20.
NOTE: pytom main needs to be updated to read this format.

Starfile annotation patch

---

setup.py

Some important bugs/issues have been fixed.
- update version to 0.2, I will add a tag in the main repo once this PR is merged
- changed to gplv2 label in setup.py corresponding with the actual license of the repo
- removed development stage label (not really applicable here)

bump to 0.2

---

README.md

Add tutorial wiki link to the README.md

---

README.md

This adds an interactive badge that shows if the tests on branch main are passing or failing

Add test badge to README.md

---

tests/test00_parallel.py
tests/test_angles.py
tests/test_extract.py
tests/test_mask.py
tests/test_template_matching.py
tests/test_tmjob.py
tests/test_weights.py

remove unnecessary 'if __name__==__main__:unittest.main()' from testfiles

---

pyproject.toml

The release of last week 0.3.5 was done on a version of the code that did not have the correct version number. So when I updated it in #109 it was still one too few.
I am also open to changing this to 0.4.0 because of the package renaming
[EDIT}: after an offline discussion we decided to go for 0.4.0 because of the name change

Update main branch version to 0.4.0

---

.github/workflows/do-release.yml
.gitignore

This is an initial try for a workflow file.
This has to be merged before I can enable secure token based uploading to PyPI and before I can run tests of this

Enable auto pypi publishing

---

pyproject.toml

let's cut a 0.4.1 release after this to see if #134 works

test updated version

---

.github/workflows/do-release.yml
pyproject.toml

this commands succesfully pulls the release from testpypi locally

Fix release workflow

---

pyproject.toml
src/pytom_tm/matching.py

Update cupy requirements

---

src/pytom_tm/entry_points.py
src/pytom_tm/tmjob.py
tests/test_entry_points.py

Closes #164 
Addition of particle diameter to calculate angular search.

calculate angular search from particle diameter

---

.github/workflows/coverage.yml
src/pytom_tm/angles.py
src/pytom_tm/extract.py
src/pytom_tm/tmjob.py

fix symmetry bug

---

.github/workflows/unit-tests.yml
.pre-commit-config.yaml
README.md
pyproject.toml
src/pytom_tm/__init__.py
src/pytom_tm/angles.py
src/pytom_tm/correlation.py
src/pytom_tm/entry_points.py
src/pytom_tm/extract.py
src/pytom_tm/io.py
src/pytom_tm/mask.py
src/pytom_tm/matching.py
src/pytom_tm/parallel.py
src/pytom_tm/plotting.py
src/pytom_tm/template.py
src/pytom_tm/tmjob.py
src/pytom_tm/utils.py
src/pytom_tm/weights.py
tests/test00_parallel.py
tests/test_angles.py
tests/test_broken_imports.py
tests/test_entry_points.py
tests/test_extract.py
tests/test_io.py
tests/test_mask.py
tests/test_template.py
tests/test_template_matching.py
tests/test_tmjob.py
tests/test_weights.py
tests/testing_utils.py

pre-commit with ruff

---

src/pytom_tm/extract.py

Need to change logging.warn to logging.warning as the former will be deprecated.

logging.warn will be deprecated

---

.github/workflows/do-release.yml
pyproject.toml

For issue #236 
I am unsure if this would solve it, but I do not know how else to diagnose it. As said in the discussion the issue sounded very similar to another reported issue. Perhaps this could fix it.
I only changed the version of the action for the test-pypi release here, as this is a test.

test if version update fixes release to test-pypi

---

.github/workflows/do-release.yml
pyproject.toml

See issue #236 for more details.
This attempts pinning to v1.11

fix action to v1.11

---

.github/workflows/do-release.yml
pyproject.toml

This should finally fix it then.

dont publish attestation to pypi

---

pyproject.toml
src/pytom_tm/extract.py
tests/test_extract.py

Solves issue #233.
@sroet, I should add a test still

fix for float16 scores for tophat

---

docs/tutorials/Tutorial.md

estimate_roc was still using 100 instead of 107, this fixes that

fix Tutorial.md

---

.github/workflows/coverage.yml
src/pytom_tm/parallel.py
tests/test_entry_points.py

Make sure we error with a reasonable message if gpus can't evenly devide number of splits

---

src/pytom_tm/tmjob.py
tests/test_tmjob.py

informative error on mask template shape mismatch
