README.md
setup.py

The estimate_roc script requires matplotlib and seaborn, so adding them as optional dependencies is the best way to do it.

Optional plotting dependency

---

tests/test_tmjob.py

Voxel size warning was printed a lot during unittest after I changed the template to have the wrong voxel size for an error assertion test. I know added another template with the wrong voxel size for that specific assertion test. Now the unittest does not clutter the terminal with voxel size warnings (which seems quite alarming).
As shown in issue #25.

added extra template file that is annotated with wrong voxel size

---

src/pytom_tm/io.py
src/pytom_tm/tmjob.py
tests/test_tmjob.py

Previous PR created some merge conflicts because main and this both changes test_tmjob.py. So this should do it.
- Function should mention volume instead of tomogram as it not only applies for tomograms.
- added error class for unequal spacing
- user is notified whether template or tomogram has unequal spacing
-  added unittest for assertion
See issue #26

patch for handling input which has unequal spacing

---

src/bin/pytom_match_template.py

Forgot to add this option to the script that was already implemented in the code.
Closes #21.

added non-spherical mask option to pytom_match_template.py

---

src/pytom_tm/io.py

Small fix to read mrc metadata in permissive mode by default.
Closes #35

default mrc metadata reading now is permissive

---

tests/test_tmjob.py

Unittests for job splitting were not consistent. Making the object non-symmetrical solved the issue on my machine and cluster. The test is even much more concise now.
See issue #25.

non-symmetrical object solves numerical incosistencies in job splitting unittest

---

src/bin/pytom_extract_candidates.py
src/pytom_tm/extract.py
tests/test_tmjob.py

This closes #36 and closes #11.
The candidate extraction accepts a mask for a specific region of interest in the tomogram. Aimed at allowing users to extract particles within some cellular context.
Also added tests to ensure masked areas are extracted (or not).

Extraction mask feature

---

src/pytom_tm/template.py

Closes #46 by updating the warning to be more verbose about which resolution is not given

Update warning for "no filter resolution"

---

src/bin/pytom_match_template.py
src/pytom_tm/io.py
src/pytom_tm/tmjob.py

Closes #29 
I added a small option to reduce angular search space for n-fold symmetrical particles.
- pytom_match_template.py has a symmetry option
- the symmetry is applied in TMJob by indexing into the angular search lists
Can this still be part of the 0.3.0 version or should I increase th version number?

reduce angular search space by applying symmetry

---

src/bin/pytom_match_template.py
src/pytom_tm/tmjob.py
tests/test_tmjob.py

This is a small change (and the last for now) to allow users to provide their own set of rotations to search the tomogram with.

Allow custom angular sampling

---

src/pytom_tm/tmjob.py
tests/test_tmjob.py
tests/test_weights.py

This PR will be part of the bugfixes for version 0.3.2. It solves issue #61.
I updated the tomogram (`tomogram_filter`) and template weighting generation (`template_wedge`) in `TMJob.start_job()` to solve this issue. After the addition of the spectrum whitening there are now quite some weighting options: a band-pass, a whitening-filter, and a wedge filter. They are optional but should also work together.
To make it more logical both weighting are now initialized as 1, and are multiplied with all the optional filters in when the respective flags are set. If they remain 1 (no filter flags are set) they will not modify the tomogram/template.
I updated the tests to run the job with combinations of these weighting options.
Also removed some debug volume writing as it interfered with clean up …

Patch band pass unassigned

---

src/pytom_tm/weights.py

One more update for version 0.3.2. I discovered online that the radial average calculation could be much faster using ndimage.mean().
Results completely overlap but the speed increase is massive:

improve radial average speed with nimdage.mean()

---

src/bin/pytom_estimate_roc.py

The change of minimal cutoff value to 0 in version 0.3.2, was not yet updated in estimate ROC. 
(sorry for commit directly to main)

update to minimal cutoff value in estimate_roc

---

tests/test_tmjob.py

Closes #58. 
It works! :relieved:
- Both the test_parallel_manager and test_tm_job_split_volume now only compare the score and angle volume with a distance of template_size // 2 from the edge as we expect numerical inaccuracies in those regions.
- test_tm_job_split_volume now splits along each dimensions (2,3,2) creating 12 subvolumes 
- test_parallel_manager still only splits (1,3,1) as this test should just check the parallel managing part

Patch unittest inconsistency

---

setup.py

PR to make sure the lastest version can be tagged under a new version number. Since the last version we patched the following:
- infamous unittest bug
- radial average calculation unified to single function
- minimal cutoff in estimate_roc now set correctly

Bump version  to 0.3.3

---

README.md

Noticed some inconsistencies in the formatting. The second pip install command was also still missing `python -m`.

Update install instruction p2

---

src/pytom_tm/parallel.py
src/pytom_tm/utils.py
tests/test_tmjob.py

Noticed a multiprocessing problem (unrelated to #74). When one of the processes fails, the other will keep running. This is undesired as the results will become unusable. Now I explicitly terminate all processes when one fails before raise a runtimeerror in the main process.
(I previsouly thought that 'raise RuntimeError' would be propagated to child processes, but that is apparently not the case)

Terminate other processes if one breaks

---

tests/00_test_parallel.py
tests/test_parallel.py
tests/test_tmjob.py

split parallel manager tests to a separate file to potentially prevent exclusive GPU process errors

parallel manager in a separate test file

---

tests/test00_parallel.py

#78 fixed the tests suite but dropped the test from discovery (it searches for `test*`), this solves that issue

unittest discover requirest testfiles to start with 'test'

---

src/pytom_tm/tmjob.py
tests/test_tmjob.py

Small patch to only calculate the whitening filter in the user specified search region. Edges of reconstructions can often have reconstruction/interpolation artifacts that users might want to avoid. The whitening filter should also not take them into account as the data here does not contain reliable info about the signal to noise ratio of the tomogram.

calculate spectrum whitening filter only in the search region

---

src/pytom_tm/matching.py

Took longer than expected. 
Some observations:
- I tried taking the sqrt before the cutoff but this failed as apparently negative values can be returned from line 201. Maybe has to do with fourier transform of a square box, which has to be approximated with infinite waves in fourier space?
- Tried setting to lower limit, but this resulted in `test_template_matching.py` finding the object back in a completely wrong position.
- Leaving it at 1 but lowering the limit works, all tests pass.
As an alternative solution, I could also normalize the search volume in each process before going to the GPU template matching structure, by doing something like:
search_volume = (search_volume - search_volume.mean())/ search_volume.std()

Standard deviation cut-off lower threshold

---

src/pytom_tm/tmjob.py
tests/test_tmjob.py

Noticed this bug this morning when I was calculating something myself. 
Apparently the subvolumes were not placed back correctly into the large subvolume when merging subjobs. This was because the whole_start parameter was not correctly calculated as I was subtracting the search_origin in x from both the x,y and z dimension. 
I first wrote a test to highlight the bug and after updating it the bug is now indeed fixed.

Subvolume indexing bug

---

src/pytom_tm/tmjob.py

I `grep`ed through the codebase and this was the only instance of `PosixPath` that came back.
This is untestable as `pathlib.WindowsPath('.')` will error out with a `NotImplementedError` on unix systems
closes #89

make json writing OS agnostic in tmjob.py

---

src/pytom_tm/template.py
tests/test_logging.py

replaces #88
I got a question from a novice user that thought it was bad when he did not specify the lowpass filter.
This now makes the log message conditional to the input
During the writing of the test I saw that there was code handeling `ctf_params=None` (line 73), so I added that option as a default to the call as well

Template.py: make filter warnings conditional and allow for no ctf_params

---

setup.py
src/bin/pytom_extract_candidates.py
src/pytom_tm/extract.py
tests/test_extract.py

This function is now quite stable and we also used it in processing some data in the group recently, so I think it would be good to merge it into the main branch and add a new version tag onto it. This way it can also be installed on the cluster. For users, the only addition to the previous version is the new '--tophat-filter' flag for pytom_extract_candidates.py. All previous functionality is identical.

experimental tophat filtering for constraining score volume peaks at extraction

---

src/pytom_tm/angles.py
src/pytom_tm/correlation.py
src/pytom_tm/extract.py
src/pytom_tm/io.py
src/pytom_tm/mask.py
src/pytom_tm/matching.py
src/pytom_tm/parallel.py
src/pytom_tm/template.py
src/pytom_tm/tmjob.py
src/pytom_tm/utils.py
src/pytom_tm/weights.py

This is a draft PR to expand and update the docstrings of the code.
This PR expands doscstrings, except for the file correlation.py where I updated some functions to first create an output return variable. In all other files its just docstrings updates.
Closes #8 
PR#100 💯

add docstrings to all functions

---

pyproject.toml
src/pytom_tm/matching.py

Temporary workaround for ReductionKernel bug in cupy 13. Code checks if cupy version 13 is installed and switch to simple 
```
def square_sum_kernel(x):
return (x ** 2).sum()
```
, instead of custom kernel.
See issue #106 for more info. The custom kernel is still preferred as it provides a ~2 x speed up.

Cupy13 workaround

---

README.md

I updated the installation instuctions in the README to prefer letting cupy build against a preinstalled cuda toolkit as the gain in performance is almost two-fold on our cluster. 
I tried building cupy against a cuda toolkit in the miniconda environment, but the result was that cupy still installed against the system installation. So I just left it as the reliable option to pull it directly from conda-forge.
related to issue #101

update install instructions to prefer building cupy

---

src/pytom_tm/extract.py
src/pytom_tm/matching.py
src/pytom_tm/tmjob.py
tests/test_tmjob.py

This PR improves the calculation of the standard deviation over a template matching search. It closes #97.
First some background on why I updated this. Template matching has a huge search space (N_voxels * rotations) which is mainly false positives, and has in comparison a tiny fraction of true positives. If we have a Gaussian for the background (with expected mean 0 and some standard deviation), the false alarm rate can be calculated for a certain cut-off value, as it is dependent on the size of the search space. For example, a false alarm rate of (N_voxels * rotations)^(-1), indicates it would expect 1 false positive in the whole search. This can be calculated with error function,
$$N^{-1} = erfc( \theta / ( \sigma \sqrt{2} ) ) / 2$$
, where theta is the cut-off, sigma the standard …

Slicing for std calculation

---

pyproject.toml
src/pytom_tm/tmjob.py
tests/test_tmjob.py

This closes #95. Whitening filter was recalculated when loading a job for particle assignment. An unnecessary step that can take quite a while for large tomograms. I added a flag to load_json_to_tmjob and the TMJob class init that can be set for particle assignment and turns off recalculation. Also added some tests around it.

Prevent whitening for extraction

---

src/pytom_tm/template.py
src/pytom_tm/tmjob.py

Two small changes here because I encountered issues with these things in the dataset I am processing.
Template generation used to do padding with edge mode (left image) and now instead pads with zeros (right). This reduces edge artifacts if the reference structure has a zeroed background (which should be the case for EM maps!).
Second change is that the template is now always multiplied with the mask before starting template matching (instead of after applying the wedge), this significantly reduces artifacts from convolution with the missing wedge. Left image is before, right image is after:

small fixes for template generation and preparation

---

.github/workflows/coverage.yml
.github/workflows/unit-tests.yml

This should add coverage and coverage reporting as a github action

add coverage reporting

---

.github/workflows/unit-tests.yml
.gitignore
pyproject.toml

This is everything that is required to enable correct multiprocess tracking for the coverage :smile: 
Also adds all the .coverage stuff to gitignore

enable coverage of the multiprocess code

---

.github/workflows/coverage.yml
src/pytom_tm/__init__.py
src/pytom_tm/extract.py
src/pytom_tm/plotting.py
tests/test_broken_imports.py

This should add coverage for the lines that deal with missing optional modules

add tests for missing libraries

---

.github/workflows/coverage.yml
.github/workflows/unit-tests.yml
pyproject.toml
tests/test00_parallel.py
tests/test_broken_imports.py
tests/test_tmjob.py
tests/test_weights.py

this tries to make sure at least all the lines in our test files are hit
closes #129

get tests to 100% coverage

---

README.md

readme update pytom-match-pick

---

tests/test00_parallel.py

Tests had a non-insignificant chance of failing due to this condition being triggerd.
I added a 1 sec wait between raising the error and seeing if all children are dead to hopefully solve this issue

Try to fix race condition in testing

---

README.md

Now that the pip install commands are working, we should update our installation instructions as well

update readme to point to pip install instead of source

---

pyproject.toml
src/pytom_tm/weights.py

This PR updates internal code in _create_tilt_weighted_wedge to create a more precise weighting function.
First I add a linear weighting up to the point where tilt image overlap in Fourier space. This now allows summation of the tilts instead of doing a maximum operation. It reduces aliasing artifacts quite a lot:
Before:
After:
The second update (which is also visible in the image, but difficult to see), is that I changed the interpolation center when tilting the images. I switched to voltools instead of ndimage.rotate as this allows me to set the center to the origin in Fourier space, while ndimage.rotate instead uses (shape - 1) / 2, which is not correct for fourier space. In the above image the wedge is shifted one pixel to the left. But this can be quite crucial for the overlap of …

ctf model ramp weighting correction and updated interpolation center

---

src/pytom_tm/entry_points.py

don't make plots for particle extraction in estimate_roc

---

src/pytom_tm/extract.py

should close #93
@McHaillet I did not see any other reference to 'ptm', however these do not have the underscore, is that correct?

change 'ptm' to 'rln' in the extraction star file

---

src/pytom_tm/entry_points.py

While running realised this issue: phase shift needs to be 0 by default otherwise None gets passed to CTF creation.

default value phase shift entry point

---

tests/test00_parallel.py

Changed from 1 to 2 seconds. You think that should be sufficient?

wait longer to prevent leaked processes

---

.github/workflows/coverage.yml
pyproject.toml
src/pytom_tm/matching.py
tests/test_template_matching.py

PR to improve the speed a bit more and setup a few things to allow easier implementation of phase randomization.
Conjugated rft's of the tomogram are precalculated (instead of template conjugation). This requires some different shifting of the output score map and a different mask for calculating the score map standard deviation (hence some changes there).
Results are consistent with previous implementation and all the tests pass.
also closes #103

small speedboost by precalculating conjugation

---

tests/test_template_matching.py

I think this should solve it.
I'll wait for the tests to pass

make template non-symmetrical for template matching test to prevent race condition

---

src/pytom_tm/entry_points.py
src/pytom_tm/extract.py
tests/test_tmjob.py

closes #177 
Coordinates are written relative to the tomogram center and in Angstrom (instead of nr of voxels). Some star file column header names also changed. 
I checked with relion what definition if of the tomogram center: 3dem/relion#1137

Relion5 compatibility

---

src/pytom_tm/template.py
tests/test_template.py

Fix for the center of mass. I am not fully sure about the unittest check yet though, maybe you have a better solution. Currently checking with the same method as I am using internally.
I also switched to box padding after recentering. That is the better order as the padding is anyway done with zeros.
Closes #173
The square seems to work nicely though. This is an example that was failing before:
And not works much better:

Center of mass fix

---

src/pytom_tm/entry_points.py
src/pytom_tm/matching.py
src/pytom_tm/template.py
src/pytom_tm/tmjob.py
tests/test_entry_points.py
tests/test_template.py
tests/test_template_matching.py

This PR adds 'phase randomization', introduced by STOPGAP.
Explanation of what this is: The match_template command line got two additional arguments: one flag to activate this mode, another to set a seed for randomization. The seed is used to create a phase randomized version of the template, meaning the phases of the Fourier transform are randomly permuted (used often for FSC calculations). This second template is like a random noise object and is matched simultaneously with the original template. The score map of the noisy version is subtracted from the real one.
With the particle diameter updated and ctf input reworked, this is the last thing I really want to add in functionality-wise.
Once this one is merged, I would like make a PR to throw the code through ruff and maybe set up a …

phase randomization score map correction

---

src/pytom_tm/entry_points.py
src/pytom_tm/extract.py
src/pytom_tm/tmjob.py
tests/test_extract.py
tests/test_tmjob.py

closes #54 
It will use the same definition as for the extraction `(any point <=0 is skipped)` but will initially only skip subvolumes where the complete mask is <= 0
For the extraction, it will use `job.tomogram_mask` as well, which can be overridden by giving a separate tomogram_mask in the entry point

Add tomogram mask option for template matching

---

README.md

This adds the DOI badge of zenodo to this repo (opted to go for the 'latest' doi and not a specific version)

Add DOI badge to readme.md

---

.github/workflows/tutorial-tests.yml

closes #148 
For now this does not include coverage
It uses repo secrets for pulling from dataverse, which means it has to be spawned like the coverage comment workflow
It walks through the tutorial file, grabs all code blocks and executes them if they start with `*.py`

add tutorial test yml

---

.github/workflows/tutorial-tests.yml

I ran and updated the tutorial today to conform with the latest version. Just realised these output dirs should be added.

fix: make output directories for tutorial tests

---

pyproject.toml

revert healpix workaround

---

pyproject.toml
src/pytom_tm/entry_points.py
tests/test_entry_points.py

bug fix: add int type for rng seed

---

pyproject.toml
src/pytom_tm/entry_points.py
src/pytom_tm/extract.py
tests/test_tmjob.py

Add ignore tomo mask option

---

src/pytom_tm/entry_points.py
src/pytom_tm/extract.py
src/pytom_tm/tmjob.py
tests/test_tmjob.py

closes #194 
(the part that the tm-job should error out if the mask is the wrong size)
Also adds the same check to the extraction job

add check on tomo mask shape

---

pyproject.toml
src/pytom_tm/angles.py
src/pytom_tm/correlation.py
src/pytom_tm/entry_points.py
src/pytom_tm/extract.py
src/pytom_tm/io.py
src/pytom_tm/mask.py
src/pytom_tm/matching.py
src/pytom_tm/parallel.py
src/pytom_tm/plotting.py
src/pytom_tm/template.py
src/pytom_tm/tmjob.py
src/pytom_tm/utils.py
src/pytom_tm/weights.py
tests/test00_parallel.py
tests/test_tmjob.py
tests/test_weights.py

add E501 check

---

src/pytom_tm/entry_points.py
src/pytom_tm/extract.py
tests/test_tmjob.py

Fixes some of the problems addressed in #214 .
* starfiles are now written with `data_particles` instead of `data_` by providing a block name to the starfile package
* a column name in relion5 compat mode has been updated from `rlnDetectorPixelSize` to `rlnTomoTiltSeriesPixelSize`

Fix relion5 compat

---

.github/workflows/tutorial-tests.yml
docs/tutorials/Tutorial.md
docs/tutorials/tests/test_tutorial.py

Alright, I am rerunning this job only on this branch until I get it working
closes #148

Get tutorial-tests.yml working

---

src/pytom_tm/entry_points.py
src/pytom_tm/io.py
tests/test_entry_points.py

add check on input gpu indices

---

pyproject.toml
src/pytom_tm/angles.py
src/pytom_tm/correlation.py
src/pytom_tm/extract.py
src/pytom_tm/io.py
src/pytom_tm/mask.py
src/pytom_tm/matching.py
src/pytom_tm/template.py
src/pytom_tm/tmjob.py
src/pytom_tm/utils.py
src/pytom_tm/weights.py

following [SPEC0](https://scientific-python.org/specs/spec-0000/)/[NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) we should probably drop python 3.9.
Also does some upgrading by running `ruff check --extend-select=UP` and either doing the auto-fix or manually fixing  the last couple

Drop py 39 and upgrade

---

.github/workflows/do-release.yml
pyproject.toml

Following the debugging done in #241, I decided to restructure the release following current best practices.
The workflow now has 4 jobs each depending on the previous one to succeed, with the type of runner in `[]`:
1) [self-hosted] build the package and test with `twine check`, upload artifact
2) [github] upload the distribution to testPyPI
3) [self-hosted] pull the latest version from testPyPI and run the test suite
4) [github] upload the distribution to PyPI

Restructure release

---

src/pytom_tm/template.py
src/pytom_tm/tmjob.py
tests/test_entry_points.py
tests/test_template.py
tests/test_tmjob.py

Currently our unit tests are failing because ruff changed some formatting rules around. This updates our files to be ruff compliant. Also updates a typo ('where asked' `->` 'were asked')

new ruff version

---

.github/workflows/tutorial-tests.yml

I had to change the files to download from dataverse as I rewrote some tutorial instructions to use a different tomogram that is a bit easier for visualization.
This is why the tests on main just failed.

fix file download for tutorial revision

---

docs/tutorials/Tutorial.md
pyproject.toml
src/pytom_tm/entry_points.py
src/pytom_tm/extract.py
tests/test_tmjob.py

This makes the extract radius parameter easier to interpret and prevents redundancy. Closes #262

Change extract radius to particle diameter for consistency

---

.github/workflows/unit-tests.yml
pyproject.toml

According to ruff, we already use code that will break on python 3.10:
```
src/pytom_tm/extract.py:250:39: SyntaxError: Cannot use star expression in index on Python 3.10 (syntax was added in Python 3.11)
|
248 |             for origin, size in zip(job.search_origin, job.search_size)
249 |         ]
250 |         tomogram_mask = tomogram_mask[*slices]
|                                       ^^^^^^^
251 |
252 |         # If tomogram_mask is stored as signed bytes we need to convert it to unsigned:
|
src/pytom_tm/tmjob.py:715:41: SyntaxError: Cannot use star expression in index on Python 3.10 (syntax was added in Python 3.11)
|
713 |                     for origin, step in zip(whole_start, sub_step)
714 |                 ]
715 |                 if np.all(tomogram_mask[*slices] <= 0):
| …
```

drop python 3.10

---

pyproject.toml
src/pytom_tm/correlation.py
src/pytom_tm/matching.py

looking through our code to see if we can up our test coverage, starting with `correlation.py`
I noticed that we have a `normalise` function that does the same thing as was implemented in `matching.py`. Updated so that `normalise` is used.
Also dropped a `mask is not None` branch from `normalised_cross_correlation` function (this function is only used in testing, specifically `test_mask.py`)
I also updated the version to account for this API change, but advise against doing a release until some actual functionality is added

actually use normalise function from correlation

---

src/pytom_tm/entry_points.py
tests/test_entry_points.py
tests/test_mask.py

This:
- adds tests for create mask entry point
- fixes a bug where if only `--radius-minor1` or `--radius-minor2` was given instead of both, we would silently create a spherical mask instead of raising an error
- add some tests for errors that can be raised from the `ellipsoidal_mask` function (making `mask.py` reach 100% 🥳 )
- rewrote test setup so that the output directory is removed and remade between tests (and uses temp directories)
- added a tests for the `_parse_argv`

add testing for create_mask

---

pyproject.toml
src/pytom_tm/tmjob.py
tests/test_tmjob.py

make sure we can load a job.json from a different directory than it was run

---

pyproject.toml
src/pytom_tm/entry_points.py
src/pytom_tm/io.py
src/pytom_tm/merge_stars.py
src/pytom_tm/parallel.py
src/pytom_tm/utils.py
tests/test_merge.py

Should close #302 
This:
Some other fixes that came in due to looking at the functions again:

swap input to starfiles instead of directories, and add absolute paths to output for pytom_merge_star.py

---

.github/workflows/unit-tests.yml

This silences TQDM in tests just to make the output nicer to read

Silence tqdm in tests

---

pyproject.toml
src/pytom_tm/entry_points.py
src/pytom_tm/tmjob.py
src/pytom_tm/weights.py
tests/test00_parallel.py
tests/test_tmjob.py
tests/test_weights.py

This:
(Was a big rewrite that needed to be done as part of #311, so decided to split it out to a separate PR)

force tilt angles for TMJob
